# Uncomment this line to define a global platform for your project
# platform :ios, '10.2'

target 'GVBandwagon' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GVBandwagon
  pod 'Firebase'
  pod 'Google'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'KGFloatingDrawer', '~> 0.2.0'
  pod 'GoogleMaps'

  target 'GVBandwagonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GVBandwagonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
